name: sogos_23
channels:
  - conda-forge
dependencies:
  - python=3.9
  - numpy
  - scipy
  
  - pandas
  - xarray
  - jupyter
  - netcdf4==1.5.4
  - gsw
  - glidertools
  - cmocean
  # - geoviews
  # - holoviews=1.14.2
  # - panel=0.11.1
  # - hvplot=0.7.1
  - plotly
  - matplotlib
  - seaborn 
  - haversine
  # - geopandas
  # - ipykernel
  - pygam
  - cartopy
  - imageio
  - rasterio
  # - hyperopt
  # - dataframe_image
  # ML Packages
  - scikit-learn
  # - pytorch
  # - torchvision
  # - keras
  # - tensorflow